#ifndef _STORAGE_BUFFER_BINDINGS_GLSL
    #define _STORAGE_BUFFER_BINDINGS_GLSL
    
    #define STORAGE_BUFFER_DRAW_INDEXES 0
    #define STORAGE_BUFFER_MATRICES 1
    #define STORAGE_BUFFER_MATERIALS 2
    //#define STORAGE_BUFFER_DIRECTIONALLIGHTS 3
    #define STORAGE_BUFFER_LIGHT_GRID 3
    #define STORAGE_BUFFER_BONES 4
    #define STORAGE_BUFFER_POINTLIGHTS 5
    #define STORAGE_BUFFER_PRIMITIVES 6
    #define STORAGE_BUFFER_LIGHTS 7
    #define STORAGE_BUFFER_DRAWCOMMANDS 8

#endif